### ISSUE TITLE
"show example" isn't text, it's showing up as a button

### ISSUE THREAD

**Issue by heyitscarloc** [heyitscarloc/heyitscarloc.github.io#27]
Reproducible Steps
1. Go to heyitscarloc.github.com

Expected results: "show examples" showing up as a link
Actual results: "show examples" shows up as a button

**Comment by heyitscarloc** [comment]
Please use span or (<a href="#" onclick="doSomething()">show examples</a>)

**Comment by paintvvitch** [comment]
removed button
